// Corporate Walk-in Jobs Sample Dataset
const DEFAULT_JOBS = [

{
  id: "walkin-prov-001",

  title: "Process Analyst - Back Office",

  company: "Provana",

  logoBg: "linear-gradient(135deg, #1F4E79, #2E75B6)",

  logoText: "PRO",

  verified: true,

  category: "Process Analyst",

  location: "Noida",

  areaDetail: "A-68, Sector 64, Noida (Nearest Metro: Sector 62)",

  package: "Up to ₹3 LPA",

  experience: "0 - 1 Yr (Freshers Eligible)",

  workingDays: "5 Days Working | Night / Rotational Shifts",

  criteria: "Graduate in any stream. Minimum age 22 years. Good command of MS Excel, good typing speed, strong communication and analytical skills. Candidates must be comfortable working in night shifts.",

  walkinDate: "2026-07-06",

  walkinDateDisplay: "6th July 2026",

  walkinTime: "10:30 AM - 03:30 PM IST",

  venue: "Provana, A-68, Sector 64, Noida, Uttar Pradesh (Nearest Metro Station: Sector 62, Noida)",

  googleMapsUrl: "https://maps.google.com/?q=Provana+A-68+Sector+64+Noida",

  contactPerson: "Rupam",

  rounds: "1. HR Screening -> 2. Assessment / Typing Test -> 3. Manager Round",

  documentsRequired: "Updated Resume, Government ID Proof (Aadhaar/PAN), Academic Documents",

  applyUrl: "https://www.provana.com/careers",

  postedDate: "2026-07-09",

  urgency: "Walk-In Hiring",

  tags: [
    "Process Analyst",
    "Back Office",
    "Non-Voice",
    "Noida",
    "Sector 64",
    "Near Sector 62 Metro",
    "Freshers Eligible",
    "Night Shift",
    "Provana"
  ]
},

  
  {
    id: "walkin-002",
    title: "Process Analyst - US Healthcare & Revenue Cycle",
    company: "Genpact India",
    logoBg: "linear-gradient(135deg, #0052D4, #4364F7)",
    logoText: "GEN",
    verified: true,
    category: "Process Analyst",
    location: "Noida",
    areaDetail: "Sector 135, Noida (SEZ Tower 3)",
    package: "₹3.8 - ₹5.5 LPA",
    experience: "0 - 3 Yrs (Freshers Welcome)",
    workingDays: "5 Days Working | US Rotational Shift",
    criteria: "Graduate (B.Com/B.A/B.Sc/B.Tech). Good verbal English, MS Excel, analytical mindset.",
    walkinDate: "2026-08-10",
    walkinDateDisplay: "10th - 12th Aug 2026",
    walkinTime: "10:00 AM - 02:00 PM IST",
    venue: "Genpact Unitech Infospace, Building 8, Sector 135, Noida, UP 201304",
    googleMapsUrl: "https://maps.google.com/?q=Genpact+Sector+135+Noida",
    contactPerson: "HR Neha Sharma / Shivam Roy",
    rounds: "1. HR Screening -> 2. Voice & Versant Test -> 3. Operations Manager Interview",
    documentsRequired: "2 Updated Resumes, Govt ID (Aadhar/PAN), Academic Certificates, Covid Vaccination Certificate",
    applyUrl: "https://www.genpact.com/careers",
    postedDate: "2026-08-07",
    urgency: "Urgent Walk-In",
    tags: ["Process Analyst", "US Shift", "Noida", "Genpact", "Freshers Eligible"]
  },
  {
    id: "walkin-003",
    title: "International Customer Support Specialist (Voice/Chat)",
    company: "Concentrix",
    logoBg: "linear-gradient(135deg, #7F00FF, #E100FF)",
    logoText: "CNX",
    verified: true,
    category: "Customer Support",
    location: "Gurugram",
    areaDetail: "Cyber City, Phase 3, Gurugram",
    package: "₹3.5 - ₹4.8 LPA + Cabs + Incentives",
    experience: "0 - 2 Yrs",
    workingDays: "5 Days Working | 2 Rotational Offs",
    criteria: "10+2 / Any Graduate. Excellent spoken English skills, typing speed > 30 WPM.",
    walkinDate: "2026-08-09",
    walkinDateDisplay: "9th - 11th Aug 2026",
    walkinTime: "10:30 AM - 03:30 PM IST",
    venue: "Concentrix Building 14, Tower C, DLF Cyber City, Gurugram, Haryana 122002",
    googleMapsUrl: "https://maps.google.com/?q=Concentrix+DLF+Cyber+City+Gurugram",
    contactPerson: "HR Pooja Malhotra",
    rounds: "1. HR Round -> 2. Voice Assessment (AMCAT) -> 3. Operations Round",
    documentsRequired: "Updated Resume, Aadhar Card, Original Marksheets, Passport Size Photos",
    applyUrl: "https://jobs.concentrix.com",
    postedDate: "2026-08-08",
    urgency: "Immediate Joining",
    tags: ["Customer Support", "Gurugram", "Voice Process", "Concentrix", "24/7 Shifts"]
  },
  {
    id: "walkin-004",
    title: "Junior IT Support Engineer & L1 Service Desk",
    company: "HCLTech",
    logoBg: "linear-gradient(135deg, #11998e, #38ef7d)",
    logoText: "HCL",
    verified: true,
    category: "IT / Software",
    location: "Noida",
    areaDetail: "Sector 126, Noida",
    package: "₹4.2 - ₹6.0 LPA",
    experience: "1 - 3 Yrs",
    workingDays: "5 Days Working | Rotational Shifts",
    criteria: "B.Tech / B.E / BCA / B.Sc IT. Basic knowledge of Active Directory, Networking, Hardware Troubleshooting, ITIL.",
    walkinDate: "2026-08-11",
    walkinDateDisplay: "11th Aug 2026 (Single Day Walk-In)",
    walkinTime: "09:30 AM - 01:30 PM IST",
    venue: "HCL Campus, A-10, Sector 126, Expressway, Noida, UP 201304",
    googleMapsUrl: "https://maps.google.com/?q=HCL+Tech+Sector+126+Noida",
    contactPerson: "HR Recruitment Team (Ref: Walk-In IT L1)",
    rounds: "1. Written Technical Aptitude -> 2. Technical Interview -> 3. HR Final",
    documentsRequired: "Hard Copy Resume, PAN & Aadhar, Last 3 Month Payslips (if experienced), College Degree",
    applyUrl: "https://www.hcltech.com/careers",
    postedDate: "2026-08-06",
    urgency: "Walk-In Drive",
    tags: ["IT Engineer", "L1 Support", "Noida", "HCLTech", "Service Desk"]
  },
  {
    id: "walkin-005",
    title: "Operations Process Associate - Financial Data Analytics",
    company: "WNS Global Services",
    logoBg: "linear-gradient(135deg, #FF416C, #FF4B2B)",
    logoText: "WNS",
    verified: true,
    category: "Process Analyst",
    location: "Gurugram",
    areaDetail: "DLF IT Park, Phase 5, Gurugram",
    package: "₹4.0 - ₹5.8 LPA",
    experience: "0 - 3 Yrs",
    workingDays: "5 Days Working | Fixed Day Shift",
    criteria: "B.Com / BBA / MBA Finance / M.Com. Strong in Advanced Excel (VLOOKUP, Pivot Tables) and Financial Reconciliation.",
    walkinDate: "2026-08-10",
    walkinDateDisplay: "10th - 13th Aug 2026",
    walkinTime: "11:00 AM - 04:00 PM IST",
    venue: "WNS Building 10, DLF Phase 5, Golf Course Road, Gurugram, Haryana 122002",
    googleMapsUrl: "https://maps.google.com/?q=WNS+DLF+Phase+5+Gurugram",
    contactPerson: "HR Ananya Verma",
    rounds: "1. Resume Screening -> 2. Excel & Domain Test -> 3. Managerial Round",
    documentsRequired: "2 Resumes, Educational Certificates, ID Proofs, Offer Letter/Relieving (if experienced)",
    applyUrl: "https://www.wns.com/careers",
    postedDate: "2026-08-08",
    urgency: "Hiring 45+ Candidates",
    tags: ["Process Associate", "Finance", "Gurugram", "WNS", "Day Shift"]
  },
  {
    id: "walkin-006",
    title: "Associate Software Developer (Java / Python / SQL)",
    company: "Tech Mahindra",
    logoBg: "linear-gradient(135deg, #ED213A, #93291E)",
    logoText: "TECHM",
    verified: true,
    category: "IT / Software",
    location: "Noida",
    areaDetail: "Sector 62, Noida",
    package: "₹4.5 - ₹6.8 LPA",
    experience: "0 - 2 Yrs",
    workingDays: "5 Days Working | Hybrid Mode",
    criteria: "B.Tech (CS/IT/ECE) or MCA with 60%+ throughout academics. Strong fundamentals in Java, SQL, Data Structures.",
    walkinDate: "2026-08-12",
    walkinDateDisplay: "12th Aug 2026",
    walkinTime: "09:00 AM - 02:00 PM IST",
    venue: "Tech Mahindra Tower B, A-6, Sector 62, Noida, UP 201309",
    googleMapsUrl: "https://maps.google.com/?q=Tech+Mahindra+Sector+62+Noida",
    contactPerson: "HR Talent Acquisition Team",
    rounds: "1. Online Coding Assessment -> 2. Technical Interview -> 3. HR Round",
    documentsRequired: "Resume, Govt ID, 10th/12th/Graduation Marksheets (Original & Xerox)",
    applyUrl: "https://www.techmahindra.com/careers/",
    postedDate: "2026-08-07",
    urgency: "Mega Walk-in Drive",
    tags: ["Software Developer", "Java", "Python", "Noida", "Tech Mahindra"]
  },
  {
    id: "walkin-007",
    title: "Technical Customer Support Executive (SaaS / Cloud)",
    company: "Teleperformance",
    logoBg: "linear-gradient(135deg, #2193b0, #6dd5ed)",
    logoText: "TP",
    verified: true,
    category: "Customer Support",
    location: "Gurugram",
    areaDetail: "Udyog Vihar Phase 3, Gurugram",
    package: "₹4.0 - ₹5.2 LPA + Shift Allowance",
    experience: "0 - 3 Yrs",
    workingDays: "5 Days Working | Rotational Shifts",
    criteria: "Any Graduate with technical aptitude. Understanding of cloud basics, ticketing tools, or technical troubleshooting.",
    walkinDate: "2026-08-09",
    walkinDateDisplay: "9th - 14th Aug 2026",
    walkinTime: "10:00 AM - 04:00 PM IST",
    venue: "Teleperformance India, Plot 96-97, Udyog Vihar Phase 3, Gurugram, Haryana 122016",
    googleMapsUrl: "https://maps.google.com/?q=Teleperformance+Udyog+Vihar+Gurugram",
    contactPerson: "HR Vivek Kumar",
    rounds: "1. Communication Round -> 2. Technical Aptitude -> 3. Ops Round",
    documentsRequired: "Updated CV, Photo ID Proof, Passport Size Photograph",
    applyUrl: "https://www.teleperformance.com/en-us/careers",
    postedDate: "2026-08-08",
    urgency: "Urgent Requirement",
    tags: ["Tech Support", "SaaS", "Gurugram", "Teleperformance"]
  },
  {
    id: "walkin-008",
    title: "Talent Acquisition Associate / HR Recruiter",
    company: "Adecco India",
    logoBg: "linear-gradient(135deg, #f12711, #f5af19)",
    logoText: "ADC",
    verified: false,
    category: "HR & Recruitment",
    location: "Noida",
    areaDetail: "Sector 63, Noida",
    package: "₹3.0 - ₹4.5 LPA + Uncapped Incentives",
    experience: "0 - 2 Yrs",
    workingDays: "5 Days Working | Day Shift (09:30 AM - 06:30 PM)",
    criteria: "MBA HR / BBA / Any Graduate. Strong communication skills, familiarity with Naukri, LinkedIn Sourcing.",
    walkinDate: "2026-08-10",
    walkinDateDisplay: "10th - 11th Aug 2026",
    walkinTime: "11:00 AM - 03:00 PM IST",
    venue: "Adecco Staffing, B-42, Sector 63, Noida, UP 201301",
    googleMapsUrl: "https://maps.google.com/?q=Adecco+Sector+63+Noida",
    contactPerson: "HR Lead Rahul Mehta",
    rounds: "1. HR Intro -> 2. Mock Candidate Sourcing Task -> 3. Branch Manager Round",
    documentsRequired: "Resume, Govt ID, Educational Marksheets",
    applyUrl: "https://www.adecco.co.in",
    postedDate: "2026-08-07",
    urgency: "Immediate Walk-In",
    tags: ["HR Recruiter", "Noida", "Day Shift", "Adecco"]
  },
  {
    id: "walkin-009",
    title: "Senior Process Analyst - Quality Assurance & Operations",
    company: "EXL Service",
    logoBg: "linear-gradient(135deg, #0F2027, #2C5364)",
    logoText: "EXL",
    verified: true,
    category: "Process Analyst",
    location: "Noida",
    areaDetail: "Sector 144, Noida Expressway",
    package: "₹5.5 - ₹8.0 LPA",
    experience: "2 - 5 Yrs",
    workingDays: "5 Days Working | UK/US Shift",
    criteria: "Graduate/Post Graduate. Min 2 years experience as QA / Process Analyst in BPO/KPO environment. Six Sigma Green Belt is a plus.",
    walkinDate: "2026-08-11",
    walkinDateDisplay: "11th - 13th Aug 2026",
    walkinTime: "10:00 AM - 03:00 PM IST",
    venue: "EXL Service Campus, Plot 7, Sector 144, Noida Expressway, UP 201306",
    googleMapsUrl: "https://maps.google.com/?q=EXL+Service+Sector+144+Noida",
    contactPerson: "HR Priya Nair",
    rounds: "1. Screening -> 2. Analytical Case Study -> 3. Operations VP Round",
    documentsRequired: "CV, Relieving Letters, Last 3 Payslips, Aadhar & PAN Card",
    applyUrl: "https://www.exlservice.com/careers",
    postedDate: "2026-08-08",
    urgency: "Mega Drive",
    tags: ["Senior Analyst", "QA", "Noida", "EXL Service"]
  },
  {
    id: "walkin-010",
    title: "Customer Service Representative (Voice) - Freshers",
    company: "TELUS Digital",
    logoBg: "linear-gradient(135deg, #2563eb, #06b6d4)",
    logoText: "TEL",
    verified: true,
    category: "BPO / Voice Process",
    location: "Noida",
    areaDetail: "Tower-6, UG Floor, Candor Techspace, Sector 135, Noida, UP 201304",
    package: "Not specified — confirm on apply",
    experience: "Freshers",
    workingDays: "Not specified",
    criteria: "Inbound calls/chats handling, wire transfer customer support",
    walkinDate: "Not currently listed for Aug 2026 — last confirmed drive was 20 Sept 2025, check live",
    walkinDateDisplay: "Not currently listed for Aug 2026 — check live",
    walkinTime: "Not specified",
    venue: "Tower-6, UG Floor, Candor Techspace, Sector 135, Noida, UP 201304",
    googleMapsUrl: "https://maps.google.com/?q=TELUS+Digital+Sector+135+Noida",
    contactPerson: "Not specified",
    rounds: "Selection process not specified — confirm on apply",
    documentsRequired: "Not specified",
    applyUrl: "https://in.talent.com/jobs/k-walk-interview-l-noida-uttar-pradesh",
    postedDate: "2026-08-08",
    urgency: "Check Live Status",
    tags: ["TELUS Digital", "Voice Process", "Noida"]
  },
  {
    id: "walkin-011",
    title: "Customer Support Executive - Voice Process",
    company: "HCL Technologies",
    logoBg: "linear-gradient(135deg, #11998e, #38ef7d)",
    logoText: "HCL",
    verified: true,
    category: "BPO / Customer Support",
    location: "Noida",
    areaDetail: "A-8 & A-9, Sector 60, Noida, UP 201301",
    package: "Not specified — confirm on apply",
    experience: "Freshers (Any Grad/UG, B.Tech/MTech/BCA/MCA not eligible for this role)",
    workingDays: "Not specified",
    criteria: "Graduate/UG, No regular students, No Law Graduates",
    walkinDate: "Not date-specific — listed as ongoing hiring",
    walkinDateDisplay: "Ongoing Hiring — Confirm Before Visit",
    walkinTime: "Not specified",
    venue: "A-8 & A-9, Sector 60, Noida, UP 201301",
    googleMapsUrl: "https://maps.google.com/?q=HCL+Technologies+Sector+60+Noida",
    contactPerson: "Not specified",
    rounds: "Selection process not specified — confirm on apply",
    documentsRequired: "Not specified",
    applyUrl: "https://in.jooble.org/jobs-walkin-interview/Sector+62-Noida",
    postedDate: "2026-08-08",
    urgency: "Ongoing Hiring",
    tags: ["HCL Technologies", "Voice Process", "Sector 60"]
  },
  {
    id: "walkin-012",
    title: "International Chat Process - Freshers",
    company: "Tech Mahindra",
    logoBg: "linear-gradient(135deg, #ED213A, #93291E)",
    logoText: "TECHM",
    verified: true,
    category: "BPO / Chat Process",
    location: "Noida",
    areaDetail: "Embassy Galaxy, Tower D, Sector 62, Noida",
    package: "Not specified — confirm on apply",
    experience: "Freshers to 4 Yrs",
    workingDays: "Not specified",
    criteria: "Any Graduate, handle international customer queries via chat",
    walkinDate: "Previously ran 1-5 June 2026 — confirm current status before visiting",
    walkinDateDisplay: "Previously ran 1-5 June 2026 — confirm current status",
    walkinTime: "Not specified",
    venue: "Embassy Galaxy, Tower D, Sector 62, Noida",
    googleMapsUrl: "https://maps.google.com/?q=Tech+Mahindra+Sector+62+Noida",
    contactPerson: "Not specified",
    rounds: "Selection process not specified — confirm on apply",
    documentsRequired: "Not specified",
    applyUrl: "https://www.fresherstech.com/tech-mahindra-walk-in-interview-for-freshers/",
    postedDate: "2026-08-08",
    urgency: "Confirm Current Status",
    tags: ["Tech Mahindra", "Chat Process", "Sector 62"]
  }
];
